/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comedorsys;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author waita
 */
public class Modificacion extends javax.swing.JPanel {

    /**
     * Creates new form Modificacion
     */
    
        //JTextField textos[];
    String ip="localhost"; //colocar la direccion de la base de dato
        String bd="bdcomedor"; //nombre de la basee de datos
        String login="root"; //usuario de la base de datos
        String password=""; //contraseña de la base de datos
        String url= "jdbc:mysql://"+ip+"/"+bd+"?useTimezone=true&serverTimezone=UTC";
        String consulf;
    
    public Modificacion() {
        initComponents();
        
        
           
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        BotonModi = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 21)); // NOI18N
        jLabel1.setText("Modificacion");

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 21)); // NOI18N
        jLabel2.setText("Lunes");

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 21)); // NOI18N
        jLabel3.setText("Martes");

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 21)); // NOI18N
        jLabel4.setText("Miercoles");

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 21)); // NOI18N
        jLabel5.setText("Jueves");

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 21)); // NOI18N
        jLabel6.setText("Viernes");

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 21)); // NOI18N
        jLabel7.setText("Plato Principal");

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 21)); // NOI18N
        jLabel8.setText("Postre");

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 21)); // NOI18N
        jLabel9.setText("Semana");

        btnBuscar.setFont(new java.awt.Font("Arial Black", 1, 21)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        BotonModi.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        BotonModi.setText("Modificar");
        BotonModi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3)
                            .addComponent(jTextField5)
                            .addComponent(jTextField7)
                            .addComponent(jTextField1)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6))
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBuscar)
                                .addGap(46, 46, 46)
                                .addComponent(BotonModi, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField10)
                            .addComponent(jTextField8)
                            .addComponent(jTextField6)
                            .addComponent(jTextField4)
                            .addComponent(jTextField2))))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar)
                        .addComponent(BotonModi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
        
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        
        try { //valida y verifica que la libreria este instalada
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Modificacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        try {
            Connection conexion = DriverManager.getConnection(url, login, password);
            if(conexion!=null){System.out.println("Connecting Historicos ["+conexion+"] OK");}
            Statement stat = conexion.createStatement(); //Permite hacer registro y consultas
            
            consulf = "SELECT * FROM menusfila WHERE dia = 'LUNES' and semana = '" + jTextField11.getText() + "'" ;
            ResultSet rs = stat.executeQuery(consulf);
            rs.next();
            jTextField1.setText(rs.getString("plato"));
            jTextField2.setText(rs.getString("postre"));
            rs.close();
            consulf = "SELECT * FROM menusfila WHERE dia = 'MARTES' and semana = '" + jTextField11.getText() + "'" ;
            rs = stat.executeQuery(consulf);
            rs.next();
            jTextField3.setText(rs.getString("plato"));
            jTextField4.setText(rs.getString("postre"));
            rs.close();
            consulf = "SELECT * FROM menusfila WHERE dia = 'MIERCOLES' and semana = '" + jTextField11.getText() + "'" ;
            rs = stat.executeQuery(consulf);
            rs.next();
            jTextField5.setText(rs.getString("plato"));
            jTextField6.setText(rs.getString("postre"));
            rs.close();
            consulf = "SELECT * FROM menusfila WHERE dia = 'JUEVES' and semana = '" + jTextField11.getText() + "'" ;
            rs = stat.executeQuery(consulf);
            rs.next();
            jTextField7.setText(rs.getString("plato"));
            jTextField8.setText(rs.getString("postre"));
            rs.close();
            consulf = "SELECT * FROM menusfila WHERE dia = 'VIERNES' and semana = '" + jTextField11.getText() + "'" ;
            rs = stat.executeQuery(consulf);
            rs.next();
            jTextField9.setText(rs.getString("plato"));
            jTextField10.setText(rs.getString("postre"));
            rs.close();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Fallo", "Error", JOptionPane.ERROR_MESSAGE);
        }
           
           //w.next();
           //JTextField textos[] = new JTextField[10];
           
           /*
           int i = 0;
           
           
           while (w.next()) //Corre cada registro de la consulta hasta fin (false)
            {
                textos[i].setText(w.getString("plato"));
                i++;
                textos[i].setText(w.getString("postre"));
                i++;
                //histogramaCanal.add(Integer.parseInt(rs.getString("contador")));
                //nombres.add(rs.getString("platos"));
            }
            w.close();
           */
           
            
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void BotonModiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModiActionPerformed
        // TODO add your handling code here:
        try { //valida y verifica que la libreria este instalada
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Modificacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        try{
            Connection conexion = DriverManager.getConnection(url, login, password);
            if(conexion!=null){System.out.println("Connecting Historicos ["+conexion+"] OK");}
            Statement stat = conexion.createStatement();
            String lunes = "UPDATE menusfila SET dia = '" + jTextField1.getText() + "', postre = '" +
                    jTextField2.getText() + "' WHERE semana = '" +jTextField11.getText() + "' and dia = 'LUNES'";
            String martes = "UPDATE menusfila SET dia = '" + jTextField3.getText() + "', postre = '" +
                    jTextField4.getText() + "' WHERE semana = '" +jTextField11.getText() + "' and dia = 'MARTES'";
            String miercoles = "UPDATE menusfila SET dia = '" + jTextField5.getText() + "', postre = '" +
                    jTextField6.getText() + "' WHERE semana = '" +jTextField11.getText() + "' and dia = 'MIERCOLES'";
            String jueves = "UPDATE menusfila SET dia = '" + jTextField7.getText() + "', postre = '" +
                    jTextField8.getText() + "' WHERE semana = '" +jTextField11.getText() + "' and dia = 'JUEVES'";
            String viernes = "UPDATE menusfila SET dia = '" + jTextField9.getText() + "', postre = '" +
                    jTextField10.getText() + "' WHERE semana = '" +jTextField11.getText() + "' and dia = 'VIERNES'";
            
            stat.executeUpdate(lunes);
            stat.executeUpdate(martes);
            stat.executeUpdate(miercoles);
            stat.executeUpdate(jueves);
            stat.executeUpdate(viernes);
            
            JOptionPane.showMessageDialog(null, "El registro fue exitoso"); //mensaje en un panel
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Fallo", "Error", JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_BotonModiActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonModi;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField4;
    public javax.swing.JTextField jTextField5;
    public javax.swing.JTextField jTextField6;
    public javax.swing.JTextField jTextField7;
    public javax.swing.JTextField jTextField8;
    public javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
