/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comedorsys;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author waita
 */
public class Modificacion extends javax.swing.JPanel {

    /**
     * Creates new form Modificacion
     */
    
        //JTextField textos[];
    String ip="192.168.2.105"; //colocar la direccion de la base de dato
        String bd="bdcomedor"; //nombre de la basee de datos
        String login="root"; //usuario de la base de datos
        String password="comedor"; //contraseña de la base de datos
        String url= "jdbc:mysql://"+ip+"/"+bd+"?useTimezone=true&serverTimezone=UTC";
        String consulf;
    
    public Modificacion() {
        initComponents();
        
        
           
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        BotonModi = new javax.swing.JButton();
        Separador = new javax.swing.JLabel();

        setBackground(new java.awt.Color(239, 235, 206));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(24, 102, 50));
        jLabel1.setText("Modificar Menu");

        jLabel2.setBackground(new java.awt.Color(24, 102, 50));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 21)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(24, 102, 50));
        jLabel2.setText("Lunes");

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 21)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(24, 102, 50));
        jLabel3.setText("Martes");

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 21)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(24, 102, 50));
        jLabel4.setText("Miercoles");

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 21)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(24, 102, 50));
        jLabel5.setText("Jueves");

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 21)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(24, 102, 50));
        jLabel6.setText("Viernes");

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 21)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(24, 102, 50));
        jLabel7.setText("Plato Principal");

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 21)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(24, 102, 50));
        jLabel8.setText("Postre");

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 21)); // NOI18N
        jLabel9.setText("Nro de semana:");

        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btnBuscar.setBackground(new java.awt.Color(28, 62, 74));
        btnBuscar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(254, 254, 254));
        btnBuscar.setText("Seleccionar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        BotonModi.setBackground(new java.awt.Color(28, 62, 74));
        BotonModi.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BotonModi.setForeground(new java.awt.Color(254, 254, 254));
        BotonModi.setText("Guardar Cambio");
        BotonModi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModiActionPerformed(evt);
            }
        });

        Separador.setFont(new java.awt.Font("Arial Black", 1, 21)); // NOI18N
        Separador.setText("----------------------------------------------------------------------------------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addGap(122, 122, 122)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextField7)
                                            .addComponent(jTextField9)
                                            .addComponent(jTextField1)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonModi))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addComponent(jLabel7))
                            .addComponent(Separador)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(496, 496, 496)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separador, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar)
                        .addComponent(BotonModi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel9))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
        
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        
        try { //valida y verifica que la libreria este instalada
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Modificacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        try {
            Connection conexion = DriverManager.getConnection(url, login, password);
            if(conexion!=null){System.out.println("Connecting Historicos ["+conexion+"] OK");}
            Statement stat = conexion.createStatement(); //Permite hacer registro y consultas
            
            if (jTextField11.getText().isEmpty()){
                JOptionPane.showMessageDialog(this,"No se ha seleccionado nada para modificar");
            }else{
            
            consulf = "SELECT * FROM menusfila WHERE dia = 'LUNES' and semana = '" + jTextField11.getText() + "'" ;
            ResultSet rs = stat.executeQuery(consulf);
            rs.next();
            
            jTextField1.setText(rs.getString("plato"));
            jTextField2.setText(rs.getString("postre"));
            rs.close();
            
            consulf = "SELECT * FROM menusfila WHERE dia = 'MARTES' and semana = '" + jTextField11.getText() + "'" ;
            rs = stat.executeQuery(consulf);
            rs.next();
            jTextField3.setText(rs.getString("plato"));
            jTextField4.setText(rs.getString("postre"));
            rs.close();
            
            consulf = "SELECT * FROM menusfila WHERE dia = 'MIERCOLES' and semana = '" + jTextField11.getText() + "'" ;
            rs = stat.executeQuery(consulf);
            rs.next();
            jTextField5.setText(rs.getString("plato"));
            jTextField6.setText(rs.getString("postre"));
            rs.close();
            
            consulf = "SELECT * FROM menusfila WHERE dia = 'JUEVES' and semana = '" + jTextField11.getText() + "'" ;
            rs = stat.executeQuery(consulf);
            rs.next();
            jTextField7.setText(rs.getString("plato"));
            jTextField8.setText(rs.getString("postre"));
            rs.close();
            
            consulf = "SELECT * FROM menusfila WHERE dia = 'VIERNES' and semana = '" + jTextField11.getText() + "'" ;
            rs = stat.executeQuery(consulf);
            rs.next();
            jTextField9.setText(rs.getString("plato"));
            jTextField10.setText(rs.getString("postre"));
            rs.close();
            }
            
            
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Fallo", "Error", JOptionPane.ERROR_MESSAGE);
        }         
            
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void BotonModiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModiActionPerformed
        // TODO add your handling code here:
        try { //valida y verifica que la libreria este instalada
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Modificacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        try{
            Connection conexion = DriverManager.getConnection(url, login, password);
            if(conexion!=null){System.out.println("Connecting Historicos ["+conexion+"] OK");}
            Statement stat = conexion.createStatement();
            
            if (jTextField1.getText().isEmpty() ||  jTextField2.getText().isEmpty() || 
                jTextField3.getText().isEmpty() || jTextField4.getText().isEmpty() || 
                    jTextField5.getText().isEmpty() || jTextField6.getText().isEmpty() || 
                    jTextField7.getText().isEmpty() || jTextField8.getText().isEmpty() || 
                    jTextField9.getText().isEmpty() || jTextField10.getText().isEmpty() ||
                    jTextField11.getText().isEmpty() ){
                JOptionPane.showMessageDialog(this,"No se admiten cuadros vacios");
            }else{
                String lunes = "UPDATE menusfila SET plato = '" + jTextField1.getText() + "', postre = '" +
                    jTextField2.getText() + "' WHERE semana = '" +jTextField11.getText() + "' and dia = 'LUNES'";
            String martes = "UPDATE menusfila SET plato = '" + jTextField3.getText() + "', postre = '" +
                    jTextField4.getText() + "' WHERE semana = '" +jTextField11.getText() + "' and dia = 'MARTES'";
            String miercoles = "UPDATE menusfila SET plato = '" + jTextField5.getText() + "', postre = '" +
                    jTextField6.getText() + "' WHERE semana = '" +jTextField11.getText() + "' and dia = 'MIERCOLES'";
            String jueves = "UPDATE menusfila SET plato = '" + jTextField7.getText() + "', postre = '" +
                    jTextField8.getText() + "' WHERE semana = '" +jTextField11.getText() + "' and dia = 'JUEVES'";
            String viernes = "UPDATE menusfila SET plato = '" + jTextField9.getText() + "', postre = '" +
                    jTextField10.getText() + "' WHERE semana = '" +jTextField11.getText() + "' and dia = 'VIERNES'";
            
            stat.executeUpdate(lunes);
            stat.executeUpdate(martes);
            stat.executeUpdate(miercoles);
            stat.executeUpdate(jueves);
            stat.executeUpdate(viernes);
            
            JOptionPane.showMessageDialog(null, "El registro fue exitoso"); //mensaje en un panel
                
            }
            
                        
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Fallo", "Error", JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_BotonModiActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonModi;
    private javax.swing.JLabel Separador;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField4;
    public javax.swing.JTextField jTextField5;
    public javax.swing.JTextField jTextField6;
    public javax.swing.JTextField jTextField7;
    public javax.swing.JTextField jTextField8;
    public javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
